# Generated by Django 4.0 on 2022-06-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='infoofuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=75)),
                ('password', models.CharField(default='', max_length=75)),
                ('email', models.CharField(default='', max_length=75)),
                ('latitude', models.CharField(default='', max_length=75)),
                ('longitude', models.CharField(default='', max_length=75)),
                ('village', models.CharField(default='', max_length=75)),
                ('taluka', models.CharField(default='', max_length=75)),
                ('district', models.CharField(default='', max_length=75)),
            ],
        ),
    ]
