# Generated by Django 4.0 on 2022-06-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_infoofuser_longitude'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=75)),
                ('password', models.CharField(default='', max_length=75)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('village', models.CharField(default='', max_length=75)),
                ('taluka', models.CharField(default='', max_length=75)),
                ('district', models.CharField(default='', max_length=75)),
                ('equipmentname', models.CharField(default='', max_length=75)),
                ('rent', models.IntegerField()),
                ('image1', models.ImageField(default='', upload_to='images')),
                ('image2', models.ImageField(default='', upload_to='images')),
                ('image3', models.ImageField(default='', upload_to='images')),
                ('image4', models.ImageField(default='', upload_to='images')),
            ],
        ),
    ]
