# Generated by Django 4.0 on 2022-06-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_equipment_image1_alter_equipment_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='company',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='equipment',
            name='old',
            field=models.IntegerField(null=True),
        ),
    ]
