# Generated by Django 4.0 on 2022-06-05 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_rename_equipment_equipment_equipment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipment1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipment_id', models.IntegerField(null=True)),
                ('username', models.CharField(default='', max_length=75)),
                ('password', models.CharField(default='', max_length=75)),
                ('latitude', models.FloatField(null=True)),
                ('longitude', models.FloatField(null=True)),
                ('phone_no', models.IntegerField(null=True)),
                ('village', models.CharField(default='', max_length=75)),
                ('taluka', models.CharField(default='', max_length=75)),
                ('district', models.CharField(default='', max_length=75)),
                ('company', models.CharField(default='', max_length=75)),
                ('old', models.IntegerField(null=True)),
                ('equipmentname', models.CharField(default='', max_length=75)),
                ('rent', models.IntegerField()),
                ('image1', models.ImageField(default='', upload_to='mainapp/images')),
                ('image2', models.ImageField(default='', upload_to='mainapp/images')),
                ('image3', models.ImageField(default='', upload_to='mainapp/images')),
                ('image4', models.ImageField(default='', upload_to='mainapp/images')),
            ],
        ),
        migrations.CreateModel(
            name='requests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(default='', max_length=75)),
                ('applicant_village', models.CharField(default='', max_length=75)),
                ('applicant_taluka', models.CharField(default='', max_length=75)),
                ('applicant_lat', models.FloatField(null=True)),
                ('applicant_long', models.FloatField(null=True)),
                ('equipment_name', models.CharField(default='', max_length=75)),
                ('equipment_id', models.IntegerField(null=True)),
                ('rent', models.IntegerField(null=True)),
                ('take_date', models.CharField(default='', max_length=75)),
                ('give_date', models.CharField(default='', max_length=75)),
                ('total_rent', models.IntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='equipment',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='infoofuser',
            name='phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
