# Generated by Django 4.0 on 2022-06-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_equipment1_requests_equipment_phone_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='applicant_phone',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='requests',
            name='equipment_holder_phone_no',
            field=models.IntegerField(null=True),
        ),
    ]
