# Generated by Django 4.0 on 2022-06-05 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_requests_applicant_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='requests_apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(default='', max_length=75)),
                ('applicant_village', models.CharField(default='', max_length=75)),
                ('applicant_taluka', models.CharField(default='', max_length=75)),
                ('applicant_phone', models.CharField(default='', max_length=75)),
                ('applicant_lat', models.FloatField(null=True)),
                ('applicant_long', models.FloatField(null=True)),
                ('equipment_name', models.CharField(default='', max_length=75)),
                ('equipment_id', models.IntegerField(null=True)),
                ('equipment_holder_phone_no', models.IntegerField(null=True)),
                ('rent', models.IntegerField(null=True)),
                ('take_date', models.CharField(default='', max_length=75)),
                ('give_date', models.CharField(default='', max_length=75)),
                ('total_rent', models.IntegerField(null=True)),
            ],
        ),
    ]
