# Generated by Django 4.0 on 2022-06-05 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_requests_apply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests_apply',
            old_name='equipment_holder_phone_no',
            new_name='equipmentholder_phone_no',
        ),
        migrations.RemoveField(
            model_name='requests_apply',
            name='applicant_lat',
        ),
        migrations.RemoveField(
            model_name='requests_apply',
            name='applicant_long',
        ),
        migrations.AddField(
            model_name='requests_apply',
            name='applicant_district',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='requests_apply',
            name='equipmentholder_district',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='requests_apply',
            name='equipmentholder_name',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='requests_apply',
            name='equipmentholder_taluka',
            field=models.CharField(default='', max_length=75),
        ),
        migrations.AddField(
            model_name='requests_apply',
            name='equipmentholder_village',
            field=models.CharField(default='', max_length=75),
        ),
    ]
