# Generated by Django 4.0 on 2022-06-05 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_rename_equipment_holder_phone_no_requests_apply_equipmentholder_phone_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipmentholder_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='equipment1',
            name='equipmentholder_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='infoofuser',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='requests_apply',
            name='applicant_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='requests_apply',
            name='equipmentholder_id',
            field=models.IntegerField(null=True),
        ),
    ]
